# Generated by Django 2.2.16 on 2020-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_avatar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
