# Generated by Django 2.2.16 on 2020-12-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_avatar_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [
                ('full_edit', 'This permission allows user to update all available fields in User model')
            ]},
        ),
    ]
