CURRENCY_USD = 1
CURRENCY_EUR = 2
CURRENCY_CHOICES = (
    (CURRENCY_USD, 'USD'),
    (CURRENCY_EUR, 'EUR')
)

SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_MINORA = 3
SOURCE_PUMB = 4
SOURCE_KREDOBANK = 5


SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'Monobank'),
    (SOURCE_MINORA, 'Minora'),
    (SOURCE_PUMB, 'PUMB'),
    (SOURCE_KREDOBANK, 'KredoBank'),
)
