# Generated by Django 2.2.16 on 2020-12-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'permissions': [
                ('full_edit', 'This permission allows user to update all available fields in Rate model')
            ]},
        ),
    ]
